apiVersion: v1
kind: Pod
metadata:
  name: python-podstate-success-test
  namespace: default
  labels:
    app: python-podstate-success-test
spec:
  containers:
  - name: python-podstate-success-test
    image: nginx:latest
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
    readinessProbe:
      httpGet:
        path: /
        port: 80
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always